name: Checks
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: pip install --upgrade pip
    - run: python3 -m pip install uv
    - run: uv sync
    - run: uv run pytest
